// <auto-generated />
using System;
using Fun88.Web.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fun88.Web.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420090404_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.CategoryTranslation", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("CategoryId", "LanguageCode")
                        .HasName("pk_category_translations");

                    b.ToTable("category_translations", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GameUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count");

                    b.Property<long>("PlayCount")
                        .HasColumnType("bigint")
                        .HasColumnName("play_count");

                    b.Property<string>("ProviderGameId")
                        .HasColumnType("text")
                        .HasColumnName("provider_game_id");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_games_slug");

                    b.HasIndex("ProviderId", "ProviderGameId")
                        .IsUnique()
                        .HasDatabaseName("ix_games_provider_id_provider_game_id")
                        .HasFilter("provider_game_id IS NOT NULL");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.GameCategory", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("GameId", "CategoryId")
                        .HasName("pk_game_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_game_categories_category_id");

                    b.ToTable("game_categories", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.GameProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_base_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_game_providers");

                    b.ToTable("game_providers", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.GameTranslation", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("ControlDescription")
                        .HasColumnType("text")
                        .HasColumnName("control_description");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text")
                        .HasColumnName("meta_description");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("text")
                        .HasColumnName("meta_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("GameId", "LanguageCode")
                        .HasName("pk_game_translations");

                    b.ToTable("game_translations", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.ScraperJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("GamesFound")
                        .HasColumnType("integer")
                        .HasColumnName("games_found");

                    b.Property<int>("GamesImported")
                        .HasColumnType("integer")
                        .HasColumnName("games_imported");

                    b.Property<int>("GamesSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("games_skipped");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_scraper_jobs");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_scraper_jobs_provider_id");

                    b.ToTable("scraper_jobs", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.TranslationJob", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<short>("AttemptCount")
                        .HasColumnType("smallint")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("GameId", "LanguageCode")
                        .HasName("pk_translation_jobs");

                    b.ToTable("translation_jobs", (string)null);
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("Fun88.Web.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_translations_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.Game", b =>
                {
                    b.HasOne("Fun88.Web.Infrastructure.Data.Entities.GameProvider", "Provider")
                        .WithMany("Games")
                        .HasForeignKey("ProviderId")
                        .HasConstraintName("fk_games_game_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.GameCategory", b =>
                {
                    b.HasOne("Fun88.Web.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany("GameCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_categories_categories_category_id");

                    b.HasOne("Fun88.Web.Infrastructure.Data.Entities.Game", "Game")
                        .WithMany("GameCategories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_categories_games_game_id");

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.GameTranslation", b =>
                {
                    b.HasOne("Fun88.Web.Infrastructure.Data.Entities.Game", "Game")
                        .WithMany("Translations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_translations_games_game_id");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.ScraperJob", b =>
                {
                    b.HasOne("Fun88.Web.Infrastructure.Data.Entities.GameProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scraper_jobs_game_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.TranslationJob", b =>
                {
                    b.HasOne("Fun88.Web.Infrastructure.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_translation_jobs_games_game_id");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Navigation("GameCategories");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.Game", b =>
                {
                    b.Navigation("GameCategories");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Fun88.Web.Infrastructure.Data.Entities.GameProvider", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
